// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czjowzxmtdzgjdbbdujo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6am93enhtdGR6Z2pkYmJkdWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDY1NjksImV4cCI6MjA2NjAyMjU2OX0.yfrOkBRwSa2FUlHk2wXNIG4yOwoTXhntlzb9-0-xfhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);